# Default Assay Configuration for Technical Filtering
# This file defines filter presets and thresholds for different analysis modes

assay_info:
  name: "default_assay"
  version: "1.0"
  genome_build: "grch38"
  description: "Default clinical sequencing panel"

# Filter configurations by mode
filter_configs:
  tumor-only:
    FILTER_PASS:
      enabled: true
      description: "Require PASS variants only"
    
    MIN_QUAL:
      enabled: true
      default: 50
      min: 20
      max: 100
      description: "Minimum variant quality score"
    
    MIN_GQ:
      enabled: true
      default: 30
      min: 10
      max: 99
      description: "Minimum genotype quality"
    
    MIN_DP:
      enabled: true
      default: 20
      min: 10
      max: 100
      description: "Minimum read depth"
    
    MIN_ALT_COUNT:
      enabled: true
      default: 10
      min: 5
      max: 50
      description: "Minimum alternate allele reads"
    
    MIN_VAF:
      enabled: true
      default: 0.05
      min: 0.01
      max: 0.5
      step: 0.01
      description: "Minimum variant allele fraction (5% for tumors)"
    
    HET_AB_RANGE:
      enabled: false  # Less relevant for tumor-only
      min_default: 0.25
      max_default: 0.75
      description: "Heterozygote allele balance range"
    
    STRAND_BIAS:
      enabled: true
      fs_max: 60
      sor_max: 3
      description: "Maximum strand bias scores"
    
    MIN_MQ:
      enabled: true
      default: 40
      min: 20
      max: 60
      description: "Minimum mapping quality"
    
    ROI_ONLY:
      enabled: true
      description: "Restrict to panel regions"
    
    MAX_POP_AF:
      enabled: true
      default: 0.01
      min: 0
      max: 0.05
      step: 0.001
      description: "Maximum population allele frequency"
    
    EFFECT_IMPACT:
      enabled: true
      default: ["HIGH", "MODERATE"]
      options: ["HIGH", "MODERATE", "LOW", "MODIFIER"]
      description: "VEP impact categories to keep"
    
    BLACKLIST:
      enabled: true
      description: "Remove known artifacts and problematic regions"

  tumor-normal:
    # Inherits all tumor-only filters with these modifications
    inherit_from: "tumor-only"
    
    MIN_VAF:
      enabled: true
      default: 0.05
      min: 0.01
      max: 0.5
      step: 0.01
      description: "Minimum VAF in tumor (somatic calling)"
    
    HET_AB_RANGE:
      enabled: true  # Important for germline subtraction
      min_default: 0.3
      max_default: 0.7
      description: "Allele balance for germline calls"
    
    NORMAL_VAF_MAX:
      enabled: true
      default: 0.02
      min: 0
      max: 0.1
      step: 0.01
      description: "Maximum VAF allowed in normal sample"
    
    TUMOR_NORMAL_VAF_RATIO:
      enabled: true
      default: 5
      min: 2
      max: 20
      description: "Minimum tumor/normal VAF ratio"

# Preset configurations for common use cases
presets:
  high_sensitivity:
    name: "High Sensitivity"
    description: "Relaxed filters for discovery mode"
    overrides:
      MIN_QUAL: 30
      MIN_DP: 15
      MIN_ALT_COUNT: 5
      MIN_VAF: 0.02
      MAX_POP_AF: 0.05
  
  high_specificity:
    name: "High Specificity"
    description: "Stringent filters for clinical reporting"
    overrides:
      MIN_QUAL: 60
      MIN_DP: 30
      MIN_ALT_COUNT: 10
      MIN_VAF: 0.10
      MAX_POP_AF: 0.001
      
  hotspot_mode:
    name: "Hotspot Mode"
    description: "Ultra-sensitive for known hotspots"
    overrides:
      MIN_QUAL: 20
      MIN_DP: 50
      MIN_ALT_COUNT: 3
      MIN_VAF: 0.01
      ROI_ONLY: true