# Technical Comments Configuration for OncoSeq Assay
# Used to annotate variants with technical caveats based on genomic context

technical_comments:
  TC001:
    id: "Coverage_Dropout"
    category: "Low or variable coverage"
    severity: "medium"
    trigger_conditions:
      - min_depth: 20
      - fraction_low_coverage_samples: 0.3
    comment_template: |
      This variant is located in a region with documented coverage dropout 
      (<{min_depth}X depth in >{fraction}% of samples). The variant call may 
      be less reliable due to insufficient read support. Manual review of BAM 
      files and consideration of orthogonal validation is recommended.
    
  TC002:
    id: "High_GC_Region"
    category: "High GC content"
    severity: "medium"
    trigger_conditions:
      - gc_content_window: 100
      - gc_threshold: 0.75
    comment_template: |
      This variant is located in a high GC content region (>{gc_percent}% GC 
      in {window}bp window). High GC regions can exhibit amplification bias 
      and uneven coverage, potentially affecting variant calling accuracy. The 
      observed allele frequency may not accurately reflect the true variant fraction.
    
  TC003:
    id: "Tandem_Repeat"
    category: "Repetitive sequences"
    severity: "high"
    trigger_conditions:
      - repeat_unit_size: [1, 6]
      - min_repeat_count: 3
    comment_template: |
      This variant occurs within a tandem repeat region. Repetitive sequences 
      can cause mapping ambiguities and alignment artifacts, leading to false 
      positive or false negative variant calls. Indel calling is particularly 
      challenging in these regions.
    
  TC004:
    id: "Systematic_Artifact"
    category: "Systematic artifacts"
    severity: "high"
    trigger_conditions:
      - min_artifact_frequency: 0.05
      - min_negative_control_count: 3
    comment_template: |
      This variant position shows recurrent technical artifacts across multiple 
      samples (>{frequency}% occurrence in negative controls). The variant call 
      may represent a systematic sequencing or library preparation artifact 
      rather than a true biological variant.
    
  TC005:
    id: "Mapping_Ambiguity"
    category: "Mapping ambiguities"
    severity: "high"
    trigger_conditions:
      - mapping_quality_threshold: 20
      - fraction_multimapped_reads: 0.2
    comment_template: |
      This variant is located in a region with significant mapping ambiguity 
      due to pseudogenes or segmental duplications. Reads may be incorrectly 
      mapped from paralogous regions, leading to spurious variant calls.
    
  TC006:
    id: "Strand_Bias"
    category: "Strand bias artifact"
    severity: "medium"
    trigger_conditions:
      - strand_bias_threshold: 0.9
      - min_alt_reads: 10
    comment_template: |
      This variant shows significant strand bias ({bias_percent}% of variant 
      reads from one strand). Strand bias can indicate PCR or sequencing 
      artifacts, oxidative damage (G>T), or FFPE deamination artifacts (C>T).
    
  TC007:
    id: "Low_Complexity"
    category: "Low complexity region"
    severity: "medium"
    trigger_conditions:
      - complexity_threshold: 1.5  # Shannon entropy
      - window_size: 50
    comment_template: |
      This variant is located in a low complexity region characterized by 
      homopolymer runs or simple sequence repeats. These regions are prone 
      to polymerase slippage and systematic indel errors.
    
  TC008:
    id: "Edge_Effect"
    category: "Amplicon/capture edge"
    severity: "low"
    trigger_conditions:
      - distance_from_edge: 10
    comment_template: |
      This variant is located within {distance}bp of a capture probe or 
      amplicon boundary. Edge effects can cause coverage dropoff and 
      increased error rates near probe boundaries.
    
  TC009:
    id: "Homopolymer_Run"
    category: "Homopolymer tract"
    severity: "high"
    trigger_conditions:
      - min_homopolymer_length: 6
      - variant_type: ["insertion", "deletion"]
    comment_template: |
      This variant is adjacent to or within a homopolymer run (≥{length} 
      identical bases). Homopolymer regions have elevated indel error rates 
      due to polymerase slippage during sequencing.
    
  TC010:
    id: "FFPE_Artifact"
    category: "FFPE-specific artifact"
    severity: "medium"
    trigger_conditions:
      - variant_patterns: ["C>T", "G>A"]
      - vaf_threshold: 0.1
      - specimen_type: "FFPE"
    comment_template: |
      This {variant_type} variant at {vaf}% allele fraction may represent 
      an FFPE deamination artifact. Formalin fixation can cause cytosine 
      deamination resulting in artifactual C>T transitions, particularly 
      at low allele fractions.
    
  TC011:
    id: "Problematic_Region_NOS"
    category: "Problematic Region NOS"
    severity: "unknown"
    trigger_conditions:
      - manual_flag: true
    comment_template: |
      This variant is located in a region flagged as problematic for technical 
      reasons not otherwise specified. Additional validation may be required 
      to confirm the variant call.

# Severity levels determine display and filtering
severity_levels:
  low:
    display_color: "yellow"
    filter_default: false
    require_review: false
  
  medium:
    display_color: "orange"
    filter_default: false
    require_review: true
  
  high:
    display_color: "red"
    filter_default: true
    require_review: true
  
  unknown:
    display_color: "gray"
    filter_default: false
    require_review: true